---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: jellyfin-media-snapshot
  namespace: jellyfin
spec:
  volumeSnapshotClassName: ebs-snapshot
  source:
    persistentVolumeClaimName: jellyfin-jellyfin-media # media pvc
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: jellyfin-config-snapshot
  namespace: jellyfin
spec:
  volumeSnapshotClassName: ebs-snapshot
  source:
    persistentVolumeClaimName: jellyfin-jellyfin-config # config pvc
