---
apiVersion: v1
kind: Service
metadata:
  name: wallabag-db
  namespace: wallabag
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: wallabag-db
  clusterIP: None
