apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: wallabag-ingress
    namespace: wallabag
    annotations:
      gethomepage.dev/description: Wallabag
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Cluster Management
      gethomepage.dev/icon: wallabag.png
      gethomepage.dev/name: Wallabag
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: wallabag.nathank.store
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: wallabag
                port:
                  number: 80
